[package]
name = "falcon_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "falcon-mc"
path = "src/main.rs"

[dependencies]
falcon_core = { path = "../core" }
falcon_protocol = { path = "../protocol" }

log = { version = "0.4", "features" = [ "release_max_level_info" ] }
log4rs = { version = "1.0", features = [ "gzip", "background_rotation" ] }
error-chain = "0.12"

flate2 = "1.0"
fastnbt = "1.2"
ahash = "0.7"
uuid = "0.8"

crossbeam = "0.8"
tokio = { version = "1.15", features = [ "full" ] }
bytes = { version = "1", features = [ "std" ] }