[package]
name = "falcon_default_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
falcon_core = { path = "../core" }
falcon_protocol = { path = "../protocol" }

log = { version = "0.4", "features" = [ "release_max_level_info" ] }
log4rs = { version = "1.0", features = [ "gzip", "background_rotation" ] }
error-chain = "0.12"

enum_dispatch = "0.3"
crossbeam = "0.8"
