[connection]
server_ip = '0.0.0.0'
server_port = 30000

[players]
allow_flight = false
max_view_distance = 10

[players.spawn_position]
x = 0.0
y = 70.0
z = 0.0

[players.spawn_look]
yaw = 0.0
pitch = 0.0

[server]
max_players = -1
description = '§eFalcon server§r§b!!!'
world = "world.schem"

[versions]
excluded = []
