[package]
name = "falcon_send"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
falcon_core = { path = "../core" }
falcon_protocol_derive = { path = "../protocol_derive" }

mc_chat = { version = "0.3.0", features = [ "serde" ] }
serde = "1.0.136"
serde_json = "1.0.79"

uuid = "0.8.2"
