[package]
name = "falcon_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
falcon_core_derive = { path = "../core_derive" }

tracing = { version = "0.1" }
error-chain = "0.12"

ahash = { version = "0.7", features = [ "serde" ] }
fastnbt = "1.2"
serde = { version = "1.0", features = [ "derive" ] }
confy = "0.4"

once_cell = "1.8"
uuid = "0.8"
bytes = "1.1"

tokio = { version = "1.15", features = [ "sync" ] }