[package]
name = "falcon_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
falcon_core_derive = { path = "../core_derive" }
mc_chat = "0.3.0"

tracing = "0.1.32"
thiserror = "1.0.30"

ahash = { version = "0.7.6", features = [ "serde" ] }
fastnbt = { git = "https://github.com/owengage/fastnbt", branch = "dev/serializer" }
serde = { version = "1.0.136", features = [ "derive" ] }
confy = "0.4.0"

itertools = "0.10.3"
ignore-result = "0.2.0"

once_cell = "1.10.0"
uuid = "0.8.2"
bytes = "1.1.0"

tokio = { version = "1.17.0", features = [ "sync" ] }
